### ISSUE TITLE
0xafC1138387a2018DA6ce0B8BC341BdE532e88f66

### ISSUE THREAD

**Issue by Miranda41** [solidproof/smart-contract-audits#30]
0xafC1138387a2018DA6ce0B8BC341BdE532e88f66

**Comment by ashkanaslama** [comment]
> 0xafC1138387a2018DA6ce0B8BC341BdE532e88f66 Please i'm not accepted for another months of waiting i need money for my kidney operation...please im begging to founder of metakings to withdraw even half of my IDO which is my token is 2615 only .and I'm highly appreciate your kindness and consideration for my sickness.
